/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufpr.view.veiculo.venda;

import br.ufpr.data.VeiculoDao;
import br.ufpr.model.Automovel;
import br.ufpr.model.Categoria;
import br.ufpr.model.Marca;
import br.ufpr.model.Veiculo;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author edenm
 */
public class JIFVender extends javax.swing.JInternalFrame {

    private VeiculoDao veiculoDao = new VeiculoDao();
    private Veiculo veiculo = new Automovel();

    /**
     * Creates new form jif_veiculo
     */
    public JIFVender() {
        initComponents();
        this.marcaVenda.setModel(new DefaultComboBoxModel(Marca.values()));
        //this.modeloVenda.setModel(new DefaultComboBoxModel(Modelo.values()));
        this.categoriaVenda.setModel(new DefaultComboBoxModel(Categoria.values()));
        table.getTable().getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                try {
                    veiculo = (Veiculo) table
                            .getSimpleReflectTableModel()
                            .getDataList()
                            .get(table
                                    .getTable()
                                    .getSelectedRow());
                    refreshForm();
                } catch (Exception ex) {
                    ex.getMessage();
                }
            }
        });
        //refreshTable(null);
    }

    private void refreshView() {
        refreshTable();
        refreshForm();
    }

    private void refreshForm() {
        

    }

    private void refreshTable() {
        try {
            Veiculo v = new Automovel();
            List l = veiculoDao.listar(veiculo);
            table.getSimpleReflectTableModel().setDataList(l);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void setaTipoAutomovel() {
        veiculo = new Automovel();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cbTipoAutomovelVenda = new javax.swing.JCheckBox();
        cbTipoMotoVenda = new javax.swing.JCheckBox();
        cbTipoVanVenda = new javax.swing.JCheckBox();
        marcaVenda = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        modeloVenda = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        table = new br.ufpr.view.util.SimpleReflectTable();
        categoriaVenda = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        filtrarVenda = new javax.swing.JButton();
        venda = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmi_VoltarTelaPrincipal = new javax.swing.JMenuItem();
        jmi_sair_do_sistema = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu_buscar = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu_alterar = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu_gravar = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu_cancelar = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Venda de Veículos");
        setMinimumSize(new java.awt.Dimension(991, 676));
        setPreferredSize(new java.awt.Dimension(991, 676));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        buttonGroupTipo.add(cbTipoAutomovelVenda);
        cbTipoAutomovelVenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipoAutomovelVenda.setText("Automóvel");
        cbTipoAutomovelVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbTipoAutomovelVendaMouseClicked(evt);
            }
        });
        cbTipoAutomovelVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoAutomovelVendaActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(cbTipoMotoVenda);
        cbTipoMotoVenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipoMotoVenda.setText("Motocicleta");
        cbTipoMotoVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbTipoMotoVendaMouseClicked(evt);
            }
        });

        buttonGroupTipo.add(cbTipoVanVenda);
        cbTipoVanVenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipoVanVenda.setText("Van");
        cbTipoVanVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbTipoVanVendaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(cbTipoAutomovelVenda)
                .addGap(18, 18, 18)
                .addComponent(cbTipoMotoVenda)
                .addGap(18, 18, 18)
                .addComponent(cbTipoVanVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbTipoAutomovelVenda, cbTipoMotoVenda});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoAutomovelVenda)
                    .addComponent(cbTipoMotoVenda)
                    .addComponent(cbTipoVanVenda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbTipoAutomovelVenda, cbTipoMotoVenda, cbTipoVanVenda});

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 30, 310, 63);

        marcaVenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        marcaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaVendaActionPerformed(evt);
            }
        });
        getContentPane().add(marcaVenda);
        marcaVenda.setBounds(370, 40, 170, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Marca");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 10, 36, 17);

        modeloVenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(modeloVenda);
        modeloVenda.setBounds(560, 40, 170, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Modelo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(590, 10, 43, 17);
        getContentPane().add(table);
        table.setBounds(70, 160, 870, 250);

        categoriaVenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoriaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaVendaActionPerformed(evt);
            }
        });
        getContentPane().add(categoriaVenda);
        categoriaVenda.setBounds(740, 40, 190, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Categoria");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(780, 10, 100, 20);

        filtrarVenda.setText("Filtrar");
        filtrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarVendaActionPerformed(evt);
            }
        });
        getContentPane().add(filtrarVenda);
        filtrarVenda.setBounds(460, 103, 80, 40);

        venda.setText("Vender");
        getContentPane().add(venda);
        venda.setBounds(560, 110, 80, 40);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 60));

        jMenu1.setText("     ");
        jMenu1.setEnabled(false);
        jMenuBar1.add(jMenu1);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/view/imagens/menu40.png"))); // NOI18N
        jMenu13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu13ActionPerformed(evt);
            }
        });
        jMenu13.add(jSeparator1);

        jmi_VoltarTelaPrincipal.setText("Voltar para tela principal");
        jmi_VoltarTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_VoltarTelaPrincipalActionPerformed(evt);
            }
        });
        jMenu13.add(jmi_VoltarTelaPrincipal);

        jmi_sair_do_sistema.setText("Sair do sistema");
        jmi_sair_do_sistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_sair_do_sistemaActionPerformed(evt);
            }
        });
        jMenu13.add(jmi_sair_do_sistema);

        jMenuBar1.add(jMenu13);

        jMenu3.setText("     ");
        jMenu3.setEnabled(false);
        jMenuBar1.add(jMenu3);

        jMenu_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/view/imagens/atualizar.png"))); // NOI18N
        jMenu_buscar.setText("BUSCAR (F5)");
        jMenu_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_buscarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_buscar);

        jMenu14.setText("     ");
        jMenuBar1.add(jMenu14);

        jMenu_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/view/imagens/edit-icon.png"))); // NOI18N
        jMenu_alterar.setText("ALTERAR (F3)");
        jMenu_alterar.setEnabled(false);
        jMenu_alterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_alterarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_alterar);

        jMenu5.setText("     ");
        jMenu5.setEnabled(false);
        jMenuBar1.add(jMenu5);

        jMenu_gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/view/imagens/salvar.png"))); // NOI18N
        jMenu_gravar.setText("GRAVAR (F4)");
        jMenu_gravar.setEnabled(false);
        jMenu_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_gravarActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_gravar);

        jMenu7.setText("     ");
        jMenu7.setEnabled(false);
        jMenuBar1.add(jMenu7);

        jMenu9.setText("     ");
        jMenu9.setEnabled(false);
        jMenuBar1.add(jMenu9);

        jMenu_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/view/imagens/Cancelar25.png"))); // NOI18N
        jMenu_cancelar.setText("CANCELAR (F6)");
        jMenu_cancelar.setEnabled(false);
        jMenuBar1.add(jMenu_cancelar);

        jMenu11.setText("     ");
        jMenuBar1.add(jMenu11);

        jMenu12.setPreferredSize(new java.awt.Dimension(100, 19));
        jMenuBar1.add(jMenu12);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu13ActionPerformed

    private void jmi_VoltarTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_VoltarTelaPrincipalActionPerformed
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_VoltarTelaPrincipalActionPerformed

    private void jmi_sair_do_sistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_sair_do_sistemaActionPerformed

        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_sair_do_sistemaActionPerformed

    private void jMenu_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_buscarMouseClicked
        jMenu_alterar.setEnabled(true);
        jMenu_cancelar.setEnabled(true);
        jMenu_gravar.setEnabled(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_buscarMouseClicked

    private void marcaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaVendaActionPerformed

    }//GEN-LAST:event_marcaVendaActionPerformed

    private void cbTipoVanVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTipoVanVendaMouseClicked
        jMenu_cancelar.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoVanVendaMouseClicked

    private void cbTipoMotoVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTipoMotoVendaMouseClicked
        jMenu_cancelar.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoMotoVendaMouseClicked

    private void cbTipoAutomovelVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoAutomovelVendaActionPerformed
        setaTipoAutomovel();
    }//GEN-LAST:event_cbTipoAutomovelVendaActionPerformed

    private void cbTipoAutomovelVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTipoAutomovelVendaMouseClicked
        jMenu_cancelar.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoAutomovelVendaMouseClicked

    private void categoriaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaVendaActionPerformed
        refreshForm();
    }//GEN-LAST:event_categoriaVendaActionPerformed

    private void jMenu_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_gravarActionPerformed

    }//GEN-LAST:event_jMenu_gravarActionPerformed

    private void jMenu_alterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_alterarMouseClicked
        jMenu_alterar.setEnabled(true);
        jMenu_cancelar.setEnabled(true);
        jMenu_gravar.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_alterarMouseClicked

    private void filtrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarVendaActionPerformed
       this.refreshTable();
    }//GEN-LAST:event_filtrarVendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JComboBox<String> categoriaVenda;
    private javax.swing.JCheckBox cbTipoAutomovelVenda;
    private javax.swing.JCheckBox cbTipoMotoVenda;
    private javax.swing.JCheckBox cbTipoVanVenda;
    private javax.swing.JButton filtrarVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_alterar;
    private javax.swing.JMenu jMenu_buscar;
    private javax.swing.JMenu jMenu_cancelar;
    private javax.swing.JMenu jMenu_gravar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem jmi_VoltarTelaPrincipal;
    private javax.swing.JMenuItem jmi_sair_do_sistema;
    private javax.swing.JComboBox<String> marcaVenda;
    private javax.swing.JComboBox<String> modeloVenda;
    private br.ufpr.view.util.SimpleReflectTable table;
    private javax.swing.JButton venda;
    // End of variables declaration//GEN-END:variables
}
