/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufpr.view.cliente;

import br.ufpr.model.Cliente;

/**
 *
 * @author edenm
 */
public class jif_clientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifClientes
     */
    public jif_clientes() {
        initComponents();
        simpleReflectTable1.setClass(Cliente.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_codigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtf_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtf_Sobrenome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcb_UF = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtf_endereco = new javax.swing.JTextField();
        jb_pesquisar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtf_RG = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtf_CPF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        simpleReflectTable1 = new br.ufpr.view.util.SimpleReflectTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jm_menuprincipalclientes = new javax.swing.JMenu();
        jm_duplicarregistro = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jm_voltatelaprincipal = new javax.swing.JMenuItem();
        jm_sairdosistema = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jb_novo = new javax.swing.JMenu();
        jm_espaco3 = new javax.swing.JMenu();
        jb_alterar = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jb_gravar = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jb_buscar = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jb_cancelar = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jb_excluir = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gerenciamento de Clientes");
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(970, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtf_codigo.setBackground(new java.awt.Color(240, 235, 240));
        jtf_codigo.setPreferredSize(new java.awt.Dimension(59, 35));
        getContentPane().add(jtf_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 51, -1, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Código");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 33, -1, -1));

        jtf_nome.setBackground(new java.awt.Color(240, 235, 240));
        jtf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 51, 311, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 33, -1, -1));

        jtf_Sobrenome.setBackground(new java.awt.Color(240, 235, 240));
        jtf_Sobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_SobrenomeActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_Sobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 51, 448, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Sobrenome");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 33, -1, -1));

        jcb_UF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcb_UF, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 128, -1, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("UF");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 107, -1, -1));

        jtf_endereco.setBackground(new java.awt.Color(240, 235, 240));
        jtf_endereco.setPreferredSize(new java.awt.Dimension(59, 35));
        getContentPane().add(jtf_endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 128, 842, 40));

        jb_pesquisar.setText("...");
        jb_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_pesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 51, 56, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Endereço");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 107, -1, -1));

        jtf_RG.setBackground(new java.awt.Color(240, 235, 240));
        getContentPane().add(jtf_RG, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 207, 190, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("RG");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 186, -1, -1));

        jtf_CPF.setBackground(new java.awt.Color(240, 235, 240));
        jtf_CPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_CPFActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 207, 178, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("CPF");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 186, -1, -1));
        getContentPane().add(simpleReflectTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 920, 190));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 60));

        jMenu1.setText("     ");
        jMenu1.setEnabled(false);
        jMenuBar1.add(jMenu1);

        jm_menuprincipalclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/view/imagens/menu40.png"))); // NOI18N
        jm_menuprincipalclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_menuprincipalclientesActionPerformed(evt);
            }
        });

        jm_duplicarregistro.setText("Duplicar registro selecionado");
        jm_duplicarregistro.setEnabled(false);
        jm_duplicarregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_duplicarregistroActionPerformed(evt);
            }
        });
        jm_menuprincipalclientes.add(jm_duplicarregistro);
        jm_menuprincipalclientes.add(jSeparator1);

        jm_voltatelaprincipal.setText("Voltar para tela principal");
        jm_voltatelaprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_voltatelaprincipalActionPerformed(evt);
            }
        });
        jm_menuprincipalclientes.add(jm_voltatelaprincipal);

        jm_sairdosistema.setText("Sair do sistema");
        jm_sairdosistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_sairdosistemaActionPerformed(evt);
            }
        });
        jm_menuprincipalclientes.add(jm_sairdosistema);

        jMenuBar1.add(jm_menuprincipalclientes);

        jMenu3.setText("     ");
        jMenu3.setEnabled(false);
        jMenuBar1.add(jMenu3);

        jb_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/view/imagens/criar25.png"))); // NOI18N
        jb_novo.setText("NOVO (F2)");
        jb_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_novoActionPerformed(evt);
            }
        });
        jMenuBar1.add(jb_novo);

        jm_espaco3.setText("     ");
        jm_espaco3.setEnabled(false);
        jMenuBar1.add(jm_espaco3);

        jb_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/view/imagens/edit-icon.png"))); // NOI18N
        jb_alterar.setText("ALTERAR (F3)");
        jb_alterar.setEnabled(false);
        jMenuBar1.add(jb_alterar);

        jMenu7.setText("     ");
        jMenu7.setEnabled(false);
        jMenuBar1.add(jMenu7);

        jb_gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/view/imagens/salvar.png"))); // NOI18N
        jb_gravar.setText("GRAVAR (F4)");
        jMenuBar1.add(jb_gravar);

        jMenu9.setText("     ");
        jMenu9.setEnabled(false);
        jMenuBar1.add(jMenu9);

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/view/imagens/atualizar.png"))); // NOI18N
        jb_buscar.setText("BUSCAR (F5)");
        jMenuBar1.add(jb_buscar);

        jMenu11.setText("     ");
        jMenu11.setEnabled(false);
        jMenuBar1.add(jMenu11);

        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/view/imagens/Cancelar25.png"))); // NOI18N
        jb_cancelar.setText("CANCELAR (F6)");
        jMenuBar1.add(jb_cancelar);

        jMenu13.setText("                                       ");
        jMenu13.setEnabled(false);
        jMenuBar1.add(jMenu13);

        jb_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/view/imagens/excluir25.png"))); // NOI18N
        jb_excluir.setText("EXCLUIR (F12)");
        jMenuBar1.add(jb_excluir);

        setJMenuBar(jMenuBar1);
    }// </editor-fold>//GEN-END:initComponents

    private void jm_duplicarregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_duplicarregistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_duplicarregistroActionPerformed

    private void jm_voltatelaprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_voltatelaprincipalActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_voltatelaprincipalActionPerformed

    private void jtf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nomeActionPerformed

    private void jtf_SobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_SobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_SobrenomeActionPerformed

    private void jm_sairdosistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_sairdosistemaActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_sairdosistemaActionPerformed

    private void jb_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_pesquisarActionPerformed
        //testar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jb_pesquisarActionPerformed

    private void jtf_CPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_CPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_CPFActionPerformed

    private void jm_menuprincipalclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_menuprincipalclientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_menuprincipalclientesActionPerformed

    private void jb_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novoActionPerformed
        //testar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jb_novoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jb_alterar;
    private javax.swing.JMenu jb_buscar;
    private javax.swing.JMenu jb_cancelar;
    private javax.swing.JMenu jb_excluir;
    private javax.swing.JMenu jb_gravar;
    private javax.swing.JMenu jb_novo;
    private javax.swing.JButton jb_pesquisar;
    private javax.swing.JComboBox<String> jcb_UF;
    private javax.swing.JMenuItem jm_duplicarregistro;
    private javax.swing.JMenu jm_espaco3;
    private javax.swing.JMenu jm_menuprincipalclientes;
    private javax.swing.JMenuItem jm_sairdosistema;
    private javax.swing.JMenuItem jm_voltatelaprincipal;
    private javax.swing.JTextField jtf_CPF;
    private javax.swing.JTextField jtf_RG;
    private javax.swing.JTextField jtf_Sobrenome;
    private javax.swing.JTextField jtf_codigo;
    private javax.swing.JTextField jtf_endereco;
    private javax.swing.JTextField jtf_nome;
    private br.ufpr.view.util.SimpleReflectTable simpleReflectTable1;
    // End of variables declaration//GEN-END:variables
}
