/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufpr.view.veiculoVender;

import br.ufpr.model.Categoria;
import br.ufpr.model.Estado;
import br.ufpr.model.Marca;
import br.ufpr.model.Veiculo;
import br.ufpr.view.util.SimpleReflectTableModel;
import java.util.Arrays;

/**
 *
 * @author edenm
 */
public class jif_veiculoVender extends javax.swing.JInternalFrame {

    /**
     * Creates new form jif_veiculo
     */
    public jif_veiculoVender() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cbTipoAutomovelVenda = new javax.swing.JCheckBox();
        cbTipoMotoVenda = new javax.swing.JCheckBox();
        cbTipoVanVenda = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jftPlacaVenda = new javax.swing.JFormattedTextField();
        jftfAnoVenda = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        cbMarcaVenda = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbModeloVenda = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jftfValorVenda = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmi_VoltarTelaPrincipal = new javax.swing.JMenuItem();
        jmi_sair_do_sistema = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu_buscar = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu_alterar = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu_gravar = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu_cancelar = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Venda de Veículos");
        setPreferredSize(new java.awt.Dimension(991, 676));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        buttonGroupTipo.add(cbTipoAutomovelVenda);
        cbTipoAutomovelVenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipoAutomovelVenda.setText("Automóvel");
        cbTipoAutomovelVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbTipoAutomovelVendaMouseClicked(evt);
            }
        });
        cbTipoAutomovelVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoAutomovelVendaActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(cbTipoMotoVenda);
        cbTipoMotoVenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipoMotoVenda.setText("Motocicleta");
        cbTipoMotoVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbTipoMotoVendaMouseClicked(evt);
            }
        });

        buttonGroupTipo.add(cbTipoVanVenda);
        cbTipoVanVenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipoVanVenda.setText("Van");
        cbTipoVanVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbTipoVanVendaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(cbTipoAutomovelVenda)
                .addGap(18, 18, 18)
                .addComponent(cbTipoMotoVenda)
                .addGap(18, 18, 18)
                .addComponent(cbTipoVanVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbTipoAutomovelVenda, cbTipoMotoVenda});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoAutomovelVenda)
                    .addComponent(cbTipoMotoVenda)
                    .addComponent(cbTipoVanVenda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbTipoAutomovelVenda, cbTipoMotoVenda, cbTipoVanVenda});

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Placa");

        jftPlacaVenda.setBackground(new java.awt.Color(240, 240, 240));
        jftPlacaVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jftfAnoVenda.setBackground(new java.awt.Color(240, 240, 240));
        jftfAnoVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ano");

        cbMarcaVenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMarcaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMarcaVendaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Marca");

        cbModeloVenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Modelo");

        jftfValorVenda.setBackground(new java.awt.Color(240, 240, 240));
        jftfValorVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Valor Venda");

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 60));

        jMenu1.setText("     ");
        jMenu1.setEnabled(false);
        jMenuBar1.add(jMenu1);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/view/imagens/menu40.png"))); // NOI18N
        jMenu13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu13ActionPerformed(evt);
            }
        });
        jMenu13.add(jSeparator1);

        jmi_VoltarTelaPrincipal.setText("Voltar para tela principal");
        jmi_VoltarTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_VoltarTelaPrincipalActionPerformed(evt);
            }
        });
        jMenu13.add(jmi_VoltarTelaPrincipal);

        jmi_sair_do_sistema.setText("Sair do sistema");
        jmi_sair_do_sistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_sair_do_sistemaActionPerformed(evt);
            }
        });
        jMenu13.add(jmi_sair_do_sistema);

        jMenuBar1.add(jMenu13);

        jMenu3.setText("     ");
        jMenu3.setEnabled(false);
        jMenuBar1.add(jMenu3);

        jMenu_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/view/imagens/atualizar.png"))); // NOI18N
        jMenu_buscar.setText("BUSCAR (F5)");
        jMenu_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_buscarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_buscar);

        jMenu14.setText("     ");
        jMenuBar1.add(jMenu14);

        jMenu_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/view/imagens/edit-icon.png"))); // NOI18N
        jMenu_alterar.setText("ALTERAR (F3)");
        jMenu_alterar.setEnabled(false);
        jMenu_alterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_alterarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_alterar);

        jMenu5.setText("     ");
        jMenu5.setEnabled(false);
        jMenuBar1.add(jMenu5);

        jMenu_gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/view/imagens/salvar.png"))); // NOI18N
        jMenu_gravar.setText("GRAVAR (F4)");
        jMenu_gravar.setEnabled(false);
        jMenuBar1.add(jMenu_gravar);

        jMenu7.setText("     ");
        jMenu7.setEnabled(false);
        jMenuBar1.add(jMenu7);

        jMenu9.setText("     ");
        jMenu9.setEnabled(false);
        jMenuBar1.add(jMenu9);

        jMenu_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/view/imagens/Cancelar25.png"))); // NOI18N
        jMenu_cancelar.setText("CANCELAR (F6)");
        jMenu_cancelar.setEnabled(false);
        jMenuBar1.add(jMenu_cancelar);

        jMenu11.setText("     ");
        jMenuBar1.add(jMenu11);

        jMenu12.setPreferredSize(new java.awt.Dimension(100, 19));
        jMenuBar1.add(jMenu12);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbMarcaVenda, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jftPlacaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(68, 68, 68)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jftfAnoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addComponent(cbModeloVenda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftfValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(1, 1, 1)
                                .addComponent(jftPlacaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jftfValorVenda, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jftfAnoVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
                        .addGap(4, 4, 4)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbModeloVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(cbMarcaVenda))
                .addContainerGap(379, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu13ActionPerformed

    private void jmi_VoltarTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_VoltarTelaPrincipalActionPerformed
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_VoltarTelaPrincipalActionPerformed

    private void jmi_sair_do_sistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_sair_do_sistemaActionPerformed

        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_sair_do_sistemaActionPerformed

    private void jMenu_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_buscarMouseClicked
           jMenu_alterar.setEnabled(true);
           jMenu_cancelar.setEnabled(true);
           jMenu_gravar.setEnabled(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_buscarMouseClicked

    private void jMenu_alterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_alterarMouseClicked
           jMenu_alterar.setEnabled(true);
           jMenu_cancelar.setEnabled(true);
           jMenu_gravar.setEnabled(true);
                   // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_alterarMouseClicked

    private void cbTipoAutomovelVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoAutomovelVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoAutomovelVendaActionPerformed

    private void cbTipoAutomovelVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTipoAutomovelVendaMouseClicked
    jMenu_cancelar.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoAutomovelVendaMouseClicked

    private void cbTipoMotoVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTipoMotoVendaMouseClicked
    jMenu_cancelar.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoMotoVendaMouseClicked

    private void cbTipoVanVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTipoVanVendaMouseClicked
    jMenu_cancelar.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoVanVendaMouseClicked

    private void cbMarcaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMarcaVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMarcaVendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JComboBox<String> cbMarcaVenda;
    private javax.swing.JComboBox<String> cbModeloVenda;
    private javax.swing.JCheckBox cbTipoAutomovelVenda;
    private javax.swing.JCheckBox cbTipoMotoVenda;
    private javax.swing.JCheckBox cbTipoVanVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_alterar;
    private javax.swing.JMenu jMenu_buscar;
    private javax.swing.JMenu jMenu_cancelar;
    private javax.swing.JMenu jMenu_gravar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JFormattedTextField jftPlacaVenda;
    private javax.swing.JFormattedTextField jftfAnoVenda;
    private javax.swing.JFormattedTextField jftfValorVenda;
    private javax.swing.JMenuItem jmi_VoltarTelaPrincipal;
    private javax.swing.JMenuItem jmi_sair_do_sistema;
    // End of variables declaration//GEN-END:variables
}
